### ISSUE TITLE
Instructions for building a local copy

### ISSUE THREAD

**Issue by sethvoltz** [smitmartijn/streamdeck-zoom-plugin#15]
I notice that the `.gitignore` file excludes the makefiles. I would like to use the new menu-clicking variant of this plugin instead of the global keys.

Is there a timeline for a release that includes those and build instructions so we can compile a local copy in the meantime?

Thanks!

**Comment by statik** [comment]
I've been using the new version published in the streamdeck store and it's been working great for me on MacOS 👍

**Comment by sethvoltz** [comment]
It doesn't work for me unless I enable the global keyboard shortcuts, which I'd like to avoid having to do.

**Comment by smitmartijn** [comment]
If you're running Windows, that still uses the key shortcuts - there is no other way there. For macOS, yes, it has been updated. The plugin in the store uses the exact same code as in this repo.

Also, the Makefiles are not there, because CMake generates them from the CMakeFiles.txt. This is a generic CMake project.
